.\" vi:set wm=5
.TH STTERM-W3M-IMG 1 "Feb 2020"
.if n .ds Q \&"
.if n .ds U \&"
.if t .ds Q ``
.if t .ds U ''
.SH NAME
stterm-w3m-img \- stterm compatible w3mimgdisplay


.SH SYNOPSIS
.B stterm-w3m-img
[ \-\fIoptions\fP ]
.ta .5i 1.8i


.SH DESCRIPTION
\fIstterm-w3m-img\fP implements the \fIw3mimgdisplay\fP remote
command protocol to display images on the terminal, using DEC
SIXEL image format.


.SH "COMMAND-LINE OPTIONS"
\fIstterm-w3m-img\fP has the following command-line options:
.TP 5
.B \-test
displays the character dimensions of the terminal.
.TP 5
.B \-size \fIIMAGE\fP
displays the pixel dimensions of the given image file.


.SH "SEE ALSO"
sixel(5) img2sixel(1)


.SH COPYRIGHT
Copyright (c) 2014 haru <uobikiemukot at gmail dot com>
.br
Copyright (c) 2020 Joseph Benden <joe@benden.us>
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
.PP
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

.SH THANKS
This software derives from the following implementations.
.br
.TP 5
.B sdump
This software includes snippets from \fIyaimg-sixel\fP, a
different w3mimgdisplay compatible program.
.br
.B https://github.com/uobikiemukot/sdump

.SH BUGS
.PD
Probable and possible. However, DO please send bug-reports,
fixes, enhancements to
.BR joe@benden.us

.\" end of man page
